{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "05f7f3d7",
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import nltk\n",
    "import re\n",
    "from nltk.corpus import stopwords\n",
    "from nltk.stem import WordNetLemmatizer\n",
    "from sklearn.model_selection import train_test_split\n",
    "from sklearn.feature_extraction.text import TfidfVectorizer\n",
    "from sklearn.linear_model import LogisticRegression\n",
    "from sklearn.metrics import accuracy_score\n",
    "import pickle"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 48,
   "id": "91d857cb",
   "metadata": {},
   "outputs": [],
   "source": [
    "df = pd.read_csv('News_sentiment_Jan2017_to_Apr2021.csv')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 49,
   "id": "e1fb1f3c",
   "metadata": {},
   "outputs": [],
   "source": [
    "df.reset_index(inplace=True, drop=True)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 50,
   "id": "668f7f08",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Date</th>\n",
       "      <th>Title</th>\n",
       "      <th>URL</th>\n",
       "      <th>sentiment</th>\n",
       "      <th>confidence</th>\n",
       "      <th>Unnamed: 5</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>05/01/17</td>\n",
       "      <td>Eliminating shadow economy to have positive im...</td>\n",
       "      <td>http://economictimes.indiatimes.com/news/econo...</td>\n",
       "      <td>POSITIVE</td>\n",
       "      <td>0.996185</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>05/01/17</td>\n",
       "      <td>Two Chinese companies hit roadblock with India...</td>\n",
       "      <td>http://economictimes.indiatimes.com/news/econo...</td>\n",
       "      <td>NEGATIVE</td>\n",
       "      <td>-0.955493</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>05/01/17</td>\n",
       "      <td>SoftBank India Vision gets new $100</td>\n",
       "      <td>http://economictimes.indiatimes.com/small-biz/...</td>\n",
       "      <td>POSITIVE</td>\n",
       "      <td>0.595612</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>05/01/17</td>\n",
       "      <td>Nissan halts joint development of luxury cars ...</td>\n",
       "      <td>http://economictimes.indiatimes.com/news/inter...</td>\n",
       "      <td>NEGATIVE</td>\n",
       "      <td>-0.996672</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>05/01/17</td>\n",
       "      <td>Despite challenges Rajasthan continues to prog...</td>\n",
       "      <td>http://economictimes.indiatimes.com/news/polit...</td>\n",
       "      <td>POSITIVE</td>\n",
       "      <td>0.997388</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>200495</th>\n",
       "      <td>12/04/21</td>\n",
       "      <td>Realme 8 5G launch date announced , specificat...</td>\n",
       "      <td>https://www.businesstoday.in/technology/realme...</td>\n",
       "      <td>POSITIVE</td>\n",
       "      <td>0.996252</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>200496</th>\n",
       "      <td>11/04/21</td>\n",
       "      <td>Bitcoin resurges beyond $60 , 000 over reports...</td>\n",
       "      <td>https://www.businesstoday.in/markets/commoditi...</td>\n",
       "      <td>NEGATIVE</td>\n",
       "      <td>-0.994247</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>200497</th>\n",
       "      <td>11/04/21</td>\n",
       "      <td>FPIs withdraw Rs 929 cr from Indian markets so...</td>\n",
       "      <td>https://www.businesstoday.in/current/economy-p...</td>\n",
       "      <td>NEGATIVE</td>\n",
       "      <td>-0.998080</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>200498</th>\n",
       "      <td>11/04/21</td>\n",
       "      <td>Google confirms Pixel 5a 5G is not cancelled ,...</td>\n",
       "      <td>https://www.businesstoday.in/technology/google...</td>\n",
       "      <td>POSITIVE</td>\n",
       "      <td>0.844368</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>200499</th>\n",
       "      <td>11/04/21</td>\n",
       "      <td>South African coronavirus variant can  break t...</td>\n",
       "      <td>https://www.businesstoday.in/sectors/pharma/so...</td>\n",
       "      <td>NEGATIVE</td>\n",
       "      <td>-0.999961</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>200500 rows × 6 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "            Date                                              Title  \\\n",
       "0       05/01/17  Eliminating shadow economy to have positive im...   \n",
       "1       05/01/17  Two Chinese companies hit roadblock with India...   \n",
       "2       05/01/17                SoftBank India Vision gets new $100   \n",
       "3       05/01/17  Nissan halts joint development of luxury cars ...   \n",
       "4       05/01/17  Despite challenges Rajasthan continues to prog...   \n",
       "...          ...                                                ...   \n",
       "200495  12/04/21  Realme 8 5G launch date announced , specificat...   \n",
       "200496  11/04/21  Bitcoin resurges beyond $60 , 000 over reports...   \n",
       "200497  11/04/21  FPIs withdraw Rs 929 cr from Indian markets so...   \n",
       "200498  11/04/21  Google confirms Pixel 5a 5G is not cancelled ,...   \n",
       "200499  11/04/21  South African coronavirus variant can  break t...   \n",
       "\n",
       "                                                      URL sentiment  \\\n",
       "0       http://economictimes.indiatimes.com/news/econo...  POSITIVE   \n",
       "1       http://economictimes.indiatimes.com/news/econo...  NEGATIVE   \n",
       "2       http://economictimes.indiatimes.com/small-biz/...  POSITIVE   \n",
       "3       http://economictimes.indiatimes.com/news/inter...  NEGATIVE   \n",
       "4       http://economictimes.indiatimes.com/news/polit...  POSITIVE   \n",
       "...                                                   ...       ...   \n",
       "200495  https://www.businesstoday.in/technology/realme...  POSITIVE   \n",
       "200496  https://www.businesstoday.in/markets/commoditi...  NEGATIVE   \n",
       "200497  https://www.businesstoday.in/current/economy-p...  NEGATIVE   \n",
       "200498  https://www.businesstoday.in/technology/google...  POSITIVE   \n",
       "200499  https://www.businesstoday.in/sectors/pharma/so...  NEGATIVE   \n",
       "\n",
       "        confidence  Unnamed: 5  \n",
       "0         0.996185         NaN  \n",
       "1        -0.955493         NaN  \n",
       "2         0.595612         NaN  \n",
       "3        -0.996672         NaN  \n",
       "4         0.997388         NaN  \n",
       "...            ...         ...  \n",
       "200495    0.996252         NaN  \n",
       "200496   -0.994247         NaN  \n",
       "200497   -0.998080         NaN  \n",
       "200498    0.844368         NaN  \n",
       "200499   -0.999961         NaN  \n",
       "\n",
       "[200500 rows x 6 columns]"
      ]
     },
     "execution_count": 50,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# df = df[:50000]\n",
    "df"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "43102215",
   "metadata": {},
   "outputs": [],
   "source": [
    "lem = WordNetLemmatizer()\n",
    "stops = stopwords.words('English')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 52,
   "id": "13c2c34c",
   "metadata": {},
   "outputs": [],
   "source": [
    "def transform(col):\n",
    "    corpus = []\n",
    "    for item in col:\n",
    "        new = re.sub('[^a-zA-Z]', ' ', str(item))\n",
    "        new = new.lower().split()\n",
    "        new = [lem.lemmatize(word) for word in new if word not in stops]\n",
    "        corpus.append(' '.join(new))\n",
    "    return corpus\n",
    "\n",
    "df['corpus'] = transform(df['Title'])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 53,
   "id": "9b3ca137",
   "metadata": {},
   "outputs": [],
   "source": [
    "x = df['corpus'].values\n",
    "y = df['sentiment'].values"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 54,
   "id": "0a6361d5",
   "metadata": {},
   "outputs": [],
   "source": [
    "tfidf = TfidfVectorizer()\n",
    "tfidf.fit(x)\n",
    "x = tfidf.transform(x)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 55,
   "id": "3827bb18",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Accuracy score is  0.7838902743142144\n"
     ]
    }
   ],
   "source": [
    "x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.1, random_state = 2, stratify = y)\n",
    "\n",
    "model = LogisticRegression(max_iter=1000)\n",
    "\n",
    "model.fit(x_train, y_train)\n",
    "\n",
    "predict = model.predict(x_test)\n",
    "\n",
    "accuracy_score = accuracy_score(predict, y_test)\n",
    "\n",
    "print('Accuracy score is ', accuracy_score)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 56,
   "id": "a7163c4f",
   "metadata": {},
   "outputs": [],
   "source": [
    "pickle.dump(model, open('data/Models/LogRegModel.pickle', 'wb'))\n",
    "pickle.dump(tfidf, open('data/Models/TfidfVec.pickle', 'wb'))\n",
    "pickle.dump(lem, open('data/Models/Lemmitizer.pickle', 'wb'))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 57,
   "id": "e7d59859",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Incorrect\n",
      "Correct\n",
      "Incorrect\n",
      "Incorrect\n",
      "Correct\n"
     ]
    }
   ],
   "source": [
    "def predictor(n):\n",
    "    x_new = x_test[n]\n",
    "    prediction = model.predict(x_new)\n",
    "\n",
    "    if prediction[0] == 'POSITIVE':\n",
    "        print('Correct')\n",
    "    else:\n",
    "        print('Incorrect')\n",
    "\n",
    "predictor(0)\n",
    "predictor(1)\n",
    "predictor(2)\n",
    "predictor(3)\n",
    "predictor(4)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 58,
   "id": "01695435",
   "metadata": {},
   "outputs": [],
   "source": [
    "df2 = pd.read_csv('Articles.csv')\n",
    "df2 = df[:10000]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 59,
   "id": "873968a5",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Date</th>\n",
       "      <th>Title</th>\n",
       "      <th>URL</th>\n",
       "      <th>sentiment</th>\n",
       "      <th>confidence</th>\n",
       "      <th>Unnamed: 5</th>\n",
       "      <th>corpus</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>05/01/17</td>\n",
       "      <td>Eliminating shadow economy to have positive im...</td>\n",
       "      <td>http://economictimes.indiatimes.com/news/econo...</td>\n",
       "      <td>POSITIVE</td>\n",
       "      <td>0.996185</td>\n",
       "      <td>NaN</td>\n",
       "      <td>eliminating shadow economy positive impact gdp...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>05/01/17</td>\n",
       "      <td>Two Chinese companies hit roadblock with India...</td>\n",
       "      <td>http://economictimes.indiatimes.com/news/econo...</td>\n",
       "      <td>NEGATIVE</td>\n",
       "      <td>-0.955493</td>\n",
       "      <td>NaN</td>\n",
       "      <td>two chinese company hit roadblock indian inves...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>05/01/17</td>\n",
       "      <td>SoftBank India Vision gets new $100</td>\n",
       "      <td>http://economictimes.indiatimes.com/small-biz/...</td>\n",
       "      <td>POSITIVE</td>\n",
       "      <td>0.595612</td>\n",
       "      <td>NaN</td>\n",
       "      <td>softbank india vision get new</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>05/01/17</td>\n",
       "      <td>Nissan halts joint development of luxury cars ...</td>\n",
       "      <td>http://economictimes.indiatimes.com/news/inter...</td>\n",
       "      <td>NEGATIVE</td>\n",
       "      <td>-0.996672</td>\n",
       "      <td>NaN</td>\n",
       "      <td>nissan halt joint development luxury car daiml...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>05/01/17</td>\n",
       "      <td>Despite challenges Rajasthan continues to prog...</td>\n",
       "      <td>http://economictimes.indiatimes.com/news/polit...</td>\n",
       "      <td>POSITIVE</td>\n",
       "      <td>0.997388</td>\n",
       "      <td>NaN</td>\n",
       "      <td>despite challenge rajasthan continues progress...</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "       Date                                              Title  \\\n",
       "0  05/01/17  Eliminating shadow economy to have positive im...   \n",
       "1  05/01/17  Two Chinese companies hit roadblock with India...   \n",
       "2  05/01/17                SoftBank India Vision gets new $100   \n",
       "3  05/01/17  Nissan halts joint development of luxury cars ...   \n",
       "4  05/01/17  Despite challenges Rajasthan continues to prog...   \n",
       "\n",
       "                                                 URL sentiment  confidence  \\\n",
       "0  http://economictimes.indiatimes.com/news/econo...  POSITIVE    0.996185   \n",
       "1  http://economictimes.indiatimes.com/news/econo...  NEGATIVE   -0.955493   \n",
       "2  http://economictimes.indiatimes.com/small-biz/...  POSITIVE    0.595612   \n",
       "3  http://economictimes.indiatimes.com/news/inter...  NEGATIVE   -0.996672   \n",
       "4  http://economictimes.indiatimes.com/news/polit...  POSITIVE    0.997388   \n",
       "\n",
       "   Unnamed: 5                                             corpus  \n",
       "0         NaN  eliminating shadow economy positive impact gdp...  \n",
       "1         NaN  two chinese company hit roadblock indian inves...  \n",
       "2         NaN                      softbank india vision get new  \n",
       "3         NaN  nissan halt joint development luxury car daiml...  \n",
       "4         NaN  despite challenge rajasthan continues progress...  "
      ]
     },
     "execution_count": 59,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df2.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 60,
   "id": "fcad00a6",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\Ad\\AppData\\Local\\Temp\\ipykernel_1928\\1327673470.py:2: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  df2['Combined'] = df2['Title']\n"
     ]
    }
   ],
   "source": [
    "# df2['Combined'] = df2['Title']+df2['Body']\n",
    "df2['Combined'] = df2['Title']"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 61,
   "id": "41ef3733",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\Ad\\AppData\\Local\\Temp\\ipykernel_1928\\1319757690.py:10: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  df2['corpus'] = transform(df2['Combined'])\n"
     ]
    }
   ],
   "source": [
    "def transform(col):\n",
    "    corpus = []\n",
    "    for item in col:\n",
    "        new = re.sub('[^a-zA-Z]', ' ', str(item))\n",
    "        new = new.lower().split()\n",
    "        new = [lem.lemmatize(word) for word in new if word not in stops]\n",
    "        corpus.append(' '.join(new))\n",
    "    return corpus\n",
    "\n",
    "df2['corpus'] = transform(df2['Combined'])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 62,
   "id": "6e09b81e",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Date</th>\n",
       "      <th>Title</th>\n",
       "      <th>URL</th>\n",
       "      <th>sentiment</th>\n",
       "      <th>confidence</th>\n",
       "      <th>Unnamed: 5</th>\n",
       "      <th>corpus</th>\n",
       "      <th>Combined</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>05/01/17</td>\n",
       "      <td>Eliminating shadow economy to have positive im...</td>\n",
       "      <td>http://economictimes.indiatimes.com/news/econo...</td>\n",
       "      <td>POSITIVE</td>\n",
       "      <td>0.996185</td>\n",
       "      <td>NaN</td>\n",
       "      <td>eliminating shadow economy positive impact gdp...</td>\n",
       "      <td>Eliminating shadow economy to have positive im...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>05/01/17</td>\n",
       "      <td>Two Chinese companies hit roadblock with India...</td>\n",
       "      <td>http://economictimes.indiatimes.com/news/econo...</td>\n",
       "      <td>NEGATIVE</td>\n",
       "      <td>-0.955493</td>\n",
       "      <td>NaN</td>\n",
       "      <td>two chinese company hit roadblock indian inves...</td>\n",
       "      <td>Two Chinese companies hit roadblock with India...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>05/01/17</td>\n",
       "      <td>SoftBank India Vision gets new $100</td>\n",
       "      <td>http://economictimes.indiatimes.com/small-biz/...</td>\n",
       "      <td>POSITIVE</td>\n",
       "      <td>0.595612</td>\n",
       "      <td>NaN</td>\n",
       "      <td>softbank india vision get new</td>\n",
       "      <td>SoftBank India Vision gets new $100</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>05/01/17</td>\n",
       "      <td>Nissan halts joint development of luxury cars ...</td>\n",
       "      <td>http://economictimes.indiatimes.com/news/inter...</td>\n",
       "      <td>NEGATIVE</td>\n",
       "      <td>-0.996672</td>\n",
       "      <td>NaN</td>\n",
       "      <td>nissan halt joint development luxury car daiml...</td>\n",
       "      <td>Nissan halts joint development of luxury cars ...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>05/01/17</td>\n",
       "      <td>Despite challenges Rajasthan continues to prog...</td>\n",
       "      <td>http://economictimes.indiatimes.com/news/polit...</td>\n",
       "      <td>POSITIVE</td>\n",
       "      <td>0.997388</td>\n",
       "      <td>NaN</td>\n",
       "      <td>despite challenge rajasthan continues progress...</td>\n",
       "      <td>Despite challenges Rajasthan continues to prog...</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "       Date                                              Title  \\\n",
       "0  05/01/17  Eliminating shadow economy to have positive im...   \n",
       "1  05/01/17  Two Chinese companies hit roadblock with India...   \n",
       "2  05/01/17                SoftBank India Vision gets new $100   \n",
       "3  05/01/17  Nissan halts joint development of luxury cars ...   \n",
       "4  05/01/17  Despite challenges Rajasthan continues to prog...   \n",
       "\n",
       "                                                 URL sentiment  confidence  \\\n",
       "0  http://economictimes.indiatimes.com/news/econo...  POSITIVE    0.996185   \n",
       "1  http://economictimes.indiatimes.com/news/econo...  NEGATIVE   -0.955493   \n",
       "2  http://economictimes.indiatimes.com/small-biz/...  POSITIVE    0.595612   \n",
       "3  http://economictimes.indiatimes.com/news/inter...  NEGATIVE   -0.996672   \n",
       "4  http://economictimes.indiatimes.com/news/polit...  POSITIVE    0.997388   \n",
       "\n",
       "   Unnamed: 5                                             corpus  \\\n",
       "0         NaN  eliminating shadow economy positive impact gdp...   \n",
       "1         NaN  two chinese company hit roadblock indian inves...   \n",
       "2         NaN                      softbank india vision get new   \n",
       "3         NaN  nissan halt joint development luxury car daiml...   \n",
       "4         NaN  despite challenge rajasthan continues progress...   \n",
       "\n",
       "                                            Combined  \n",
       "0  Eliminating shadow economy to have positive im...  \n",
       "1  Two Chinese companies hit roadblock with India...  \n",
       "2                SoftBank India Vision gets new $100  \n",
       "3  Nissan halts joint development of luxury cars ...  \n",
       "4  Despite challenges Rajasthan continues to prog...  "
      ]
     },
     "execution_count": 62,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df2.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 63,
   "id": "0c578e74",
   "metadata": {},
   "outputs": [],
   "source": [
    "x2 = df2['corpus'].values\n",
    "x2 = tfidf.transform(x2)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 64,
   "id": "5534e51c",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "0.8127\n"
     ]
    }
   ],
   "source": [
    "pred2 = model.predict(x2)\n",
    "c = 0\n",
    "ic = 0\n",
    "for i in range(len(pred2)):\n",
    "    if pred2[i].lower() == df2['sentiment'][i].lower():\n",
    "        c += 1\n",
    "    else:\n",
    "        ic += 1\n",
    "#         print(pred2[i], df2['sentiment'][i], df2['Title'][i])\n",
    "\n",
    "print(c/(c+ic))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "9fb430bb",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "dac8b1c3",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "6aba9d5a",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "ae859576",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "ac807e11",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "fcb3d891",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "206db826",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
